### ISSUE TITLE
pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by wangtianrui** [RoyJames/pygsound#5]
after:
sudo apt-get update
sudo apt-get -y install cmake python3-dev gobjc++ libfftw3-dev

I run the following code :
(python3) root@iZ2zeab8t820b30ezwjthjZ:~/pygsound# python3 setup.py develop
running develop
running egg_info
writing dependency_links to src/pygsound.egg-info/dependency_links.txt
writing src/pygsound.egg-info/PKG-INFO
writing top-level names to src/pygsound.egg-info/top_level.txt
writing requirements to src/pygsound.egg-info/requires.txt
reading manifest file 'src/pygsound.egg-info/SOURCES.txt'
writing manifest file 'src/pygsound.egg-info/SOURCES.txt'
running build_ext
-- Found PythonInterp: /root/.virtualenvs/python3/bin/python3 (found version "3.5.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- pybind11 v2.4.dev4
-- CMAKE_SYSTEM_NAME          = Linux
-- CMAKE_CXX_COMPILER_ID      = GNU
-- CMAKE_CXX_COMPILER_VERSION = 5.4.0
-- CMAKE_COMPILER_IS_GNUCXX   = 1
Python dir: /usr/include/python3.5m
Python lib: /root/.virtualenvs/python3/lib/python3.5/config-3.5m-x86_64-linux-gnu
Building pygsound release library
-- Configuring done
-- Generating done
-- Build files have been written to: /root/pygsound/build/temp.linux-x86_64-3.5
[ 28%] Built target om-framework
[ 32%] Built target om-bvh
[ 38%] Built target om-resources
[ 64%] Built target om-sound
[ 93%] Built target gsound
[ 94%] Building CXX object src/pygsound/CMakeFiles/pygsound.dir/src/Scene.cpp.o
In file included from /root/pygsound/lib/pybind11/include/pybind11/pytypes.h:12:0,
                 from /root/pygsound/lib/pybind11/include/pybind11/cast.h:13,
                 from /root/pygsound/lib/pybind11/include/pybind11/attr.h:13,
                 from /root/pygsound/lib/pybind11/include/pybind11/pybind11.h:44,
                 from /root/pygsound/src/pygsound/src/Python.hpp:4,
                 from /root/pygsound/src/pygsound/src/SoundSource.hpp:4,
                 from /root/pygsound/src/pygsound/src/Scene.cpp:1:
/root/pygsound/lib/pybind11/include/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or directory
compilation terminated.
src/pygsound/CMakeFiles/pygsound.dir/build.make:107: recipe for target 'src/pygsound/CMakeFiles/pygsound.dir/src/Scene.cpp.o' failed
make[2]: *** [src/pygsound/CMakeFiles/pygsound.dir/src/Scene.cpp.o] Error 1
CMakeFiles/Makefile2:399: recipe for target 'src/pygsound/CMakeFiles/pygsound.dir/all' failed
make[1]: *** [src/pygsound/CMakeFiles/pygsound.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    'wavefile',
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/root/.virtualenvs/python3/lib/python3.5/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 36, in run
    self.build_extension(ext)
  File "setup.py", line 68, in build_extension
    cwd=self.build_temp)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release']' returned non-zero exit status 2

how can I fix this problem? (python-dev and python3-dev are already installed, Python.h is available),thank you very much!

**Comment by RoyJames** [comment]
The python in your virtualenv is 3.5.2. What is the system-level python3 version? They need to be consistent for the virtualenv to find python3-dev. If that's not the case, try using conda to create a virtual env with python version the same as the system python.
